name: ServerCoreTest
version: 1.0
api-version: 1.13
main: nyeblock.Core.ServerCoreTest.Main
depend: [Multiverse-Core, WorldEdit]
commands:
  setpermission:
    description: Set the permission for a player
    usage: /setpermission <player> <permission> <value>
  force-start:
    description: Force start the game you are in
    usage: /forcestart
  ban:
    description: Ban the specific player for the specified amount of time
    usage: /ban <player> <length in minutes> <reason>
  banIp:
    description: Ban the specified ip
    usage: /banIp <ip> <length in minutes> <reason>